version: '3'

services:
  backend:
    build: ./backend/
    ports:
      - '9000:9000'
    volumes:
      - ./backend/:/weatherapp/backend
      - /weatherapp/backend/node_modules
    env_file:
      - .env

  frontend:
    build: ./frontend/
    ports:
      - '8000:8000'
    volumes:
      - ./frontend/:/weatherapp/frontend
      - /weatherapp/frontend/node_modules
    depends_on:
      - backend
    links:
      - backend